language: python

python:
  - 2.7

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

install:
  - pip install beautifulsoup4
  - pip install requests
  - pip install pandas
  - pip install sqlalchemy sqlalchemy-utils
  - pip install coveralls
  - pip install MySQL-python

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -ppassword -e "create database IF NOT EXISTS tardis;"

script:
  - nosetests --with-coverage

after_success:
  - coveralls

after-failure:
  - cat /home/travis/.pip/pip.log