language: python

python:
  - 2.7

install:
  - pip install beautifulsoup4
  - pip install requests
  - pip install pandas
  - pip install sqlalchemy
  - pip install coveralls

script:
  - nosetests --with-coverage

after_success:
  - coveralls

after-failure:
  - cat /home/travis/.pip/pip.log